// Generated by gencpp from file kinova_arm_moveit_demo/PhantomButtonEvent.msg
// DO NOT EDIT!


#ifndef KINOVA_ARM_MOVEIT_DEMO_MESSAGE_PHANTOMBUTTONEVENT_H
#define KINOVA_ARM_MOVEIT_DEMO_MESSAGE_PHANTOMBUTTONEVENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinova_arm_moveit_demo
{
template <class ContainerAllocator>
struct PhantomButtonEvent_
{
  typedef PhantomButtonEvent_<ContainerAllocator> Type;

  PhantomButtonEvent_()
    : grey_button(0)
    , white_button(0)  {
    }
  PhantomButtonEvent_(const ContainerAllocator& _alloc)
    : grey_button(0)
    , white_button(0)  {
  (void)_alloc;
    }



   typedef int32_t _grey_button_type;
  _grey_button_type grey_button;

   typedef int32_t _white_button_type;
  _white_button_type white_button;





  typedef boost::shared_ptr< ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator> const> ConstPtr;

}; // struct PhantomButtonEvent_

typedef ::kinova_arm_moveit_demo::PhantomButtonEvent_<std::allocator<void> > PhantomButtonEvent;

typedef boost::shared_ptr< ::kinova_arm_moveit_demo::PhantomButtonEvent > PhantomButtonEventPtr;
typedef boost::shared_ptr< ::kinova_arm_moveit_demo::PhantomButtonEvent const> PhantomButtonEventConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator1> & lhs, const ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator2> & rhs)
{
  return lhs.grey_button == rhs.grey_button &&
    lhs.white_button == rhs.white_button;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator1> & lhs, const ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kinova_arm_moveit_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb77877e6b639935c3360838062f05f0";
  }

  static const char* value(const ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb77877e6b639935ULL;
  static const uint64_t static_value2 = 0xc3360838062f05f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinova_arm_moveit_demo/PhantomButtonEvent";
  }

  static const char* value(const ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 grey_button\n"
"int32 white_button\n"
;
  }

  static const char* value(const ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grey_button);
      stream.next(m.white_button);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PhantomButtonEvent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinova_arm_moveit_demo::PhantomButtonEvent_<ContainerAllocator>& v)
  {
    s << indent << "grey_button: ";
    Printer<int32_t>::stream(s, indent + "  ", v.grey_button);
    s << indent << "white_button: ";
    Printer<int32_t>::stream(s, indent + "  ", v.white_button);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINOVA_ARM_MOVEIT_DEMO_MESSAGE_PHANTOMBUTTONEVENT_H
