// Generated by gencpp from file color_depth_msg/colordepth.msg
// DO NOT EDIT!


#ifndef COLOR_DEPTH_MSG_MESSAGE_COLORDEPTH_H
#define COLOR_DEPTH_MSG_MESSAGE_COLORDEPTH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>

namespace color_depth_msg
{
template <class ContainerAllocator>
struct colordepth_
{
  typedef colordepth_<ContainerAllocator> Type;

  colordepth_()
    : color()
    , depth()  {
    }
  colordepth_(const ContainerAllocator& _alloc)
    : color(_alloc)
    , depth(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _color_type;
  _color_type color;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _depth_type;
  _depth_type depth;





  typedef boost::shared_ptr< ::color_depth_msg::colordepth_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::color_depth_msg::colordepth_<ContainerAllocator> const> ConstPtr;

}; // struct colordepth_

typedef ::color_depth_msg::colordepth_<std::allocator<void> > colordepth;

typedef boost::shared_ptr< ::color_depth_msg::colordepth > colordepthPtr;
typedef boost::shared_ptr< ::color_depth_msg::colordepth const> colordepthConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::color_depth_msg::colordepth_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::color_depth_msg::colordepth_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::color_depth_msg::colordepth_<ContainerAllocator1> & lhs, const ::color_depth_msg::colordepth_<ContainerAllocator2> & rhs)
{
  return lhs.color == rhs.color &&
    lhs.depth == rhs.depth;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::color_depth_msg::colordepth_<ContainerAllocator1> & lhs, const ::color_depth_msg::colordepth_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace color_depth_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::color_depth_msg::colordepth_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::color_depth_msg::colordepth_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::color_depth_msg::colordepth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::color_depth_msg::colordepth_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::color_depth_msg::colordepth_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::color_depth_msg::colordepth_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::color_depth_msg::colordepth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b5aeff90d2304214393960f2a5a3312";
  }

  static const char* value(const ::color_depth_msg::colordepth_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b5aeff90d230421ULL;
  static const uint64_t static_value2 = 0x4393960f2a5a3312ULL;
};

template<class ContainerAllocator>
struct DataType< ::color_depth_msg::colordepth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "color_depth_msg/colordepth";
  }

  static const char* value(const ::color_depth_msg::colordepth_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::color_depth_msg::colordepth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image  color\n"
"sensor_msgs/Image  depth\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::color_depth_msg::colordepth_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::color_depth_msg::colordepth_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
      stream.next(m.depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct colordepth_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::color_depth_msg::colordepth_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::color_depth_msg::colordepth_<ContainerAllocator>& v)
  {
    s << indent << "color: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.color);
    s << indent << "depth: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.depth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLOR_DEPTH_MSG_MESSAGE_COLORDEPTH_H
